#!/bin/bash

conf_file=/usr/local/fail2tc/fail2tc.properties
ip_addr=$1
text_port=$2
port_int=`grep ssh /etc/services | cut -f3 | cut -d"/" -f1 | uniq`
credentials=`grep credentials= $conf_file | cut -d= -f2`
url=`grep url= $conf_file | cut -d= -f2`
with_port_template=`grep indicator_with_port= $conf_file | cut -d= -f2`
without_port_template=`grep indicator_without_port= $conf_file | cut -d= -f2`

if [ -z "$port_int" ]; then
  json_text=$without_port_template
else
  json_text=$with_port_template
fi

json_text=${json_text/@service_name@/$text_port}
json_text=${json_text/@port_int@/$port_int}
json_text=${json_text/@ip_addr@/$ip_addr}

curl -XPOST -u $credentials -H "content-type: application/json" -H "accept: application/json" --basic -d "$json_text" $url/rest/indicators
